FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /tmp/requirements.txt

RUN pip install \
    --no-cache-dir \
    --disable-pip-version-check \
    -r /tmp/requirements.txt

WORKDIR /sandbox


# To run:
#
# cd C:\UCY\EPL-thesis\EPL-thesis\Clone
# docker build `
#     -f agents\codeTester\Dockerfile.code-tester `
#     -t epl-code-tester:latest `
#     .