''' Imports '''
# Langchain imports
from langchain_core.messages import SystemMessage, AIMessage, BaseMessage, ToolMessage, HumanMessage
from langchain_core.tools import tool

# Langgraph imports
from langgraph.graph import StateGraph, MessagesState
from langgraph.checkpoint.memory import MemorySaver
from langgraph.constants import END, START
from langgraph.prebuilt import ToolNode

# Schema imports
from typing import TypedDict, Literal, List, Optional, Annotated, Union, Dict, Any
from pydantic import BaseModel, Field
from operator import add

# General imports
from dotenv import load_dotenv
from pathlib import Path
from time import sleep
import traceback
import json
import os

# My imports
from utils.utils import myChatOpenAI, safe_invoke, print_function_name, will_tool_call, parse_tool_arguments, USER_APPROVALS, read_state_file, clean_llm_output
from creations.whatsapp_receipt_agent import whatsapp_receipt_agent_prompts as prompts

import re
from PIL import Image, ImageFilter
from io import BytesIO
from datetime import datetime
from paddleocr import PaddleOCR
import numpy as np

import requests

import openpyxl



''' Constants '''
load_dotenv(dotenv_path= Path(__file__).resolve().parent.parent.parent / '.env')

DEBUG = os.getenv('DEBUG')

BLUE = '\033[94m' # INFO
RED = '\033[91m' # ERR
GREEN = '\033[92m' # REST
RESET = '\033[0m'



print(f'\n{BLUE}[AGENT] [INFO] [STARTUP]{RESET} whatsapp_receipt_agent') if DEBUG else None



""" Schemas """
class ReceiptData(BaseModel):
    """
    Schema for structured receipt data extracted by OCR. Used within the AgentSchema to store parsed receipt information.
    """
    cost: float # Total cost of the receipt.
    date: str # Date of the receipt in YYYY-MM-DD format.
    items: str # Formatted string of items, e.g., 'item1 (quantity x price currency), ...'.
    location: str # Location where the receipt was issued.
    category: str # Automatically determined category of the receipt (e.g., 'Groceries', 'Coffee').

class AgentSchema(MessagesState):
    """
    Main schema for the WhatsApp Receipt Agent's state. It holds conversation history, current processing mode, next action, pending questions, and extracted receipt data. This schema is used as the state for the LangGraph graph.
    """
    mode: str # Current processing mode of the agent (e.g., 'process_receipt', 'ocr_failed', 'chat').
    next_action: str # Indicates the next action the agent expects or will take (e.g., 'confirm_receipt', 'ocr_failed', 'query_spending').
    pending_question: str # Stores the last question asked to the user if clarification is needed.
    last_seen_event_id: str # ID of the last processed event to prevent duplicate processing.
    latest: str # The latest assistant reply generated by the agent.
    receipt_data: Optional[ReceiptData] # Structured data extracted from a receipt photo, if available. Uses the ReceiptData schema.



''' Tools '''
@tool
def currency_converter(amount: float, from_currency: str, to_currency: str) -> float:
    """
    Overview: Converts an amount from one currency to another using static, predefined exchange rates. This tool is used to normalize currency values, primarily to Euro, for consistent financial reporting. The exchange rates are hardcoded within the tool.
    
    Caller LLM: chat_llm
    
    Outside-the-Tool Work (Tool Handler Function Responsibilities): None. The caller LLM will use the returned float directly in its reasoning or response generation.
    
    Inside-the-Tool Work (Tool Responsibilities): This tool performs the actual currency conversion using a fixed set of exchange rates defined internally.
    
    Instructions:
    1. Accept `amount`, `from_currency`, and `to_currency`.
    2. Access a predefined dictionary of static exchange rates (e.g., {'USD_EUR': 0.85, 'GBP_EUR': 1.15, 'EUR_USD': 1.18, 'EUR_GBP': 0.87}).
    3. Construct a key from `from_currency` and `to_currency` (e.g., 'USD_EUR').
    4. If the direct rate is available, multiply the `amount` by this rate.
    5. If the inverse rate is available (e.g., 'EUR_USD' for 'USD_EUR' conversion), divide the `amount` by this rate.
    6. If neither direct nor inverse rate is found, return the original `amount` and log a warning (or raise an error, depending on desired robustness, but for simplicity, returning original amount is acceptable for now).
    7. Return the converted amount as a float.
    
    State Updates (on the caller function): None. The caller LLM will use the returned float directly.
    
    Args:
        amount (float): The numerical amount to be converted.
        from_currency (str): The currency code of the original amount (e.g., 'USD', 'GBP', 'EUR').
        to_currency (str): The currency code to convert to (e.g., 'EUR').
    
    Returns:
        float: The converted amount.
    """
    # Handle edge case where currencies are the same
    if from_currency == to_currency:
        return amount
    
    # Define static exchange rates
    rates = {
        'USD_EUR': 0.85,
        'GBP_EUR': 1.15,
        'EUR_USD': 1.18,
        'EUR_GBP': 0.87,
        'CHF_EUR': 0.92,
        'EUR_CHF': 1.09
    }
    
    # Construct the direct key
    direct_key = f"{from_currency}_{to_currency}"
    
    # Check if direct rate is available
    if direct_key in rates:
        return amount * rates[direct_key]
    
    # Construct the inverse key
    inverse_key = f"{to_currency}_{from_currency}"
    
    # Check if inverse rate is available
    if inverse_key in rates:
        return amount / rates[inverse_key]
    
    # If neither rate is found, log warning and return original amount
    print(f'{RED}[TOOL] [WARN]{RESET} No exchange rate found for {from_currency} to {to_currency}, returning original amount.')
    return amount

@tool
def tavily_search(query: str) -> dict:
    """
    Overview: Performs a web search using the Tavily API to retrieve external context or information. This tool is used by the `chat` node to clarify ambiguous user queries or to gather additional relevant information for a response.
    
    Caller LLM: chat_llm
    
    Outside-the-Tool Work (Tool Handler Function Responsibilities): None. The caller LLM will use the returned search results directly in its reasoning or response generation.
    
    Inside-the-Tool Work (Tool Responsibilities): This tool sends the `query` to the Tavily search API and returns the search results.
    
    Instructions:
    1. Accept a `query` string.
    2. Use the Tavily API (requires `TAVILY_API_KEY` environment variable) to perform a web search with the given `query`.
    3. Process the raw search results from Tavily.
    4. Extract and format relevant information, such as a direct answer and a list of sources.
    5. Return the processed results in a structured dictionary format (e.g., containing 'answer', 'sources', 'raw_results').
    
    State Updates (on the caller function): None. The caller LLM will use the returned dictionary directly.
    
    Args:
        query (str): The search query string.
    
    Returns:
        dict: A dictionary containing the search results, typically including an 'answer' and 'sources'.
    """
    try:
        # Validate query parameter
        if not query or not query.strip():
            return {
                'answer': 'Error: Search query cannot be empty.',
                'sources': []
            }
        
        # Get the API key from environment variables
        api_key: str = os.getenv('TAVILY_API_KEY')
        
        if not api_key:
            return {
                'answer': 'Error: TAVILY_API_KEY environment variable is not set.',
                'sources': []
            }
        
        # Define the API endpoint
        url: str = 'https://api.tavily.com/search'
        
        # Construct the payload
        payload: dict = {
            'api_key': api_key,
            'query': query.strip(),
            'search_depth': 'basic',
            'include_answer': True,
            'max_results': 5
        }
        
        # Make the POST request
        response = requests.post(url, json=payload, timeout=30)
        
        # Check for HTTP errors
        response.raise_for_status()
        
        # Parse the JSON response
        response_data: dict = response.json()
        
        # Extract the answer
        answer: str = response_data.get('answer', 'No answer found.')
        
        # Extract and format sources as list of dicts for better structure
        sources: list = []
        results: list = response_data.get('results', [])
        
        for result in results:
            title: str = result.get('title', '').strip()
            url: str = result.get('url', '').strip()
            # Only include sources with valid URLs
            if url:
                sources.append({
                    'title': title if title else 'Unknown Title',
                    'url': url
                })
        
        # Return the structured results
        return {
            'answer': answer,
            'sources': sources
        }
        
    except requests.exceptions.RequestException as e:
        print(f'{RED}[TOOL] [ERR]{RESET} Request error in tavily_search: {e}')
        traceback.print_exc()
        return {
            'answer': 'Error: Failed to perform search. Please try again later.',
            'sources': []
        }
    except ValueError as e:
        # Handle JSON decode errors
        print(f'{RED}[TOOL] [ERR]{RESET} JSON parsing error in tavily_search: {e}')
        traceback.print_exc()
        return {
            'answer': 'Error: Failed to parse search response. Please try again later.',
            'sources': []
        }
    except Exception as e:
        print(f'{RED}[TOOL] [ERR]{RESET} Error in tavily_search: {e}')
        traceback.print_exc()
        return {
            'answer': 'Error: An unexpected error occurred. Please try again later.',
            'sources': []
        }

@tool
def write_row_excel(data: ReceiptData) -> dict:
    """
    Overview: Writes a single row of receipt data to the local Excel file (`.xlsx`). This tool handles appending new receipt information to the persistent storage.
    
    Caller LLM: chat_llm (for confirming OCR results), ocr_processing_llm (for saving extracted data)
    
    Outside-the-Tool Work (Tool Handler Function Responsibilities): None. The caller LLM will use the returned status to generate a confirmation or error message for the user.
    
    Inside-the-Tool Work (Tool Responsibilities): This tool manages the file I/O operation to append a new row to the local Excel file.
    
    Instructions:
    1. Receive `data` (a `ReceiptData` object) to be written.
    2. Open the local Excel file (e.g., 'receipts.xlsx' in the agent's directory). If the file does not exist, create it with appropriate headers.
    3. Append the `data` as a new row, mapping `ReceiptData` fields to columns: cost, date, items, location, category.
    4. Save the Excel file.
    5. Return a dictionary indicating success or failure (e.g., `{'status': 'success'}` or `{'status': 'failure', 'reason': 'File not found'}`).
    
    State Updates (on the caller function): None. The caller node will update `state.messages` with confirmation or error messages based on the tool's output.
    
    Args:
        data (ReceiptData): The structured receipt data to write to the Excel file.
    
    Returns:
        dict: A dictionary indicating the status of the operation. For writes: `{'status': 'success'}` or `{'status': 'failure', 'reason': '...'}`.
    """
    try:
        # Validate that data is a ReceiptData instance
        if not isinstance(data, ReceiptData):
            return {'status': 'failure', 'reason': 'Invalid data type: expected ReceiptData instance'}
        
        # Validate required fields are not None or empty
        required_fields = {
            'cost': data.cost,
            'date': data.date,
            'items': data.items,
            'location': data.location,
            'category': data.category
        }
        
        for field_name, field_value in required_fields.items():
            if field_value is None:
                return {'status': 'failure', 'reason': f'Missing required field: {field_name} is None'}
            if isinstance(field_value, str) and field_value.strip() == '':
                return {'status': 'failure', 'reason': f'Missing required field: {field_name} is empty'}
        
        # Validate cost is a valid non-negative number
        if not isinstance(data.cost, (int, float)):
            return {'status': 'failure', 'reason': f'Invalid cost type: expected number, got {type(data.cost).__name__}'}
        if data.cost < 0:
            return {'status': 'failure', 'reason': f'Invalid cost value: {data.cost} is negative'}
        
        # Define the Excel file path in the same directory as the agent
        excel_file: Path = Path(__file__).resolve().parent / 'receipts.xlsx'
        
        # Try to load existing workbook, or create new one if it doesn't exist
        wb = None
        try:
            wb = openpyxl.load_workbook(str(excel_file))
            ws = wb.active
        except FileNotFoundError:
            # File doesn't exist, create new workbook with headers
            wb = openpyxl.Workbook()
            ws = wb.active
            headers: list[str] = ['cost', 'date', 'items', 'location', 'category']
            ws.append(headers)
        
        # Extract data from the ReceiptData object
        row_data: list = [
            data.cost,
            data.date,
            data.items,
            data.location,
            data.category
        ]
        
        # Append the new row
        ws.append(row_data)
        
        # Save the workbook
        wb.save(str(excel_file))
        
        return {'status': 'success'}
        
    except PermissionError as e:
        print(f'{RED}[TOOL] [ERR]{RESET} Permission error writing to Excel file: {e}')
        return {'status': 'failure', 'reason': f'Permission denied: {str(e)}'}
    except OSError as e:
        print(f'{RED}[TOOL] [ERR]{RESET} OS error writing to Excel file: {e}')
        return {'status': 'failure', 'reason': f'File system error: {str(e)}'}
    except Exception as e:
        print(f'{RED}[TOOL] [ERR]{RESET} Error writing to Excel file: {e}')
        traceback.print_exc()
        return {'status': 'failure', 'reason': str(e)}
    finally:
        # Ensure workbook is always closed to prevent file-lock issues
        if wb is not None:
            try:
                wb.close()
            except Exception:
                pass

@tool
def read_excel(query: Optional[dict]) -> dict:
    """
    Overview: Reads receipt data from the local Excel file (`.xlsx`). This tool retrieves stored receipt information, optionally applying filters, for analysis and reporting.
    
    Caller LLM: chat_llm (for answering spending queries)
    
    Outside-the-Tool Work (Tool Handler Function Responsibilities): None. The caller LLM will use the returned data to formulate a user-facing reply.
    
    Inside-the-Tool Work (Tool Responsibilities): This tool manages the file I/O operation to read data from the local Excel file.
    
    Instructions:
    1. Receive an optional `query` dictionary (e.g., `{'category': 'Groceries', 'date': '2023-10'}`).
    2. Open the local Excel file (e.g., 'receipts.xlsx' in the agent's directory).
    3. Read all rows from the Excel file.
    4. If a `query` is provided, filter the rows based on the query parameters (e.g., match 'category' or 'date').
    5. Convert the read (and filtered) data into a list of `ReceiptData` objects or dictionaries.
    6. Return a dictionary containing the retrieved data (e.g., `{'data': List[ReceiptData]}`).
    
    State Updates (on the caller function): None. The caller node will update `state.messages` with the final reply based on the tool's output.
    
    Args:
        query (Optional[dict]): A dictionary of filters to apply when reading data (e.g., `{'category': 'Groceries', 'date': '2023-10'}`). If None, all data is read.
    
    Returns:
        dict: A dictionary containing the retrieved data. For reads: `{'data': List[ReceiptData]}`.
    """
    # Initialize workbook variable to None before try block for proper cleanup
    wb = None
    
    try:
        # Define the Excel file path in the same directory as the agent
        excel_file: Path = Path(__file__).resolve().parent / 'receipts.xlsx'
        
        # Try to load existing workbook
        wb = openpyxl.load_workbook(str(excel_file))
        ws = wb.active
        
        # Read the header row to identify column indices
        headers: list[str] = []
        for cell in ws[1]:
            if cell.value:
                headers.append(str(cell.value).strip().lower())
        
        # Validate that required columns exist
        required_columns = ['cost', 'date', 'items', 'location', 'category']
        column_indices: dict[str, int] = {}
        for col in required_columns:
            if col in headers:
                column_indices[col] = headers.index(col)
            else:
                # Column not found, return empty data
                return {'data': []}
        
        # Read all data rows
        all_data: list[dict] = []
        for row in ws.iter_rows(min_row=2, values_only=True):
            # Skip empty rows
            if not row or all(cell is None for cell in row):
                continue
            
            # Create a dictionary for the row
            row_data: dict = {}
            for col, idx in column_indices.items():
                if idx < len(row):
                    row_data[col] = row[idx]
                else:
                    row_data[col] = None
            
            # Only add rows that have at least some data
            if any(v is not None for v in row_data.values()):
                all_data.append(row_data)
        
        # If no query provided, return all data
        if query is None or not query:
            return {'data': all_data}
        
        # Apply filters based on query parameters
        filtered_data: list[dict] = []
        for row in all_data:
            match = True
            
            # Filter by category (exact match, case-insensitive)
            if 'category' in query and query['category']:
                row_category = str(row.get('category', '')).strip()
                if row_category.lower() != str(query['category']).strip().lower():
                    match = False
            
            # Filter by date (prefix match, e.g., '2023-10' matches '2023-10-15')
            if match and 'date' in query and query['date']:
                row_date = str(row.get('date', '')).strip()
                query_date = str(query['date']).strip()
                if not row_date.startswith(query_date):
                    match = False
            
            # Filter by location (exact match, case-insensitive)
            if match and 'location' in query and query['location']:
                row_location = str(row.get('location', '')).strip()
                if row_location.lower() != str(query['location']).strip().lower():
                    match = False
            
            if match:
                filtered_data.append(row)
        
        return {'data': filtered_data}
        
    except FileNotFoundError:
        # File doesn't exist, return empty data
        print(f'{RED}[TOOL] [WARN]{RESET} Excel file not found, returning empty data.')
        return {'data': []}
        
    except PermissionError as e:
        print(f'{RED}[TOOL] [ERR]{RESET} Permission error reading Excel file: {e}')
        return {'data': []}
        
    except Exception as e:
        print(f'{RED}[TOOL] [ERR]{RESET} Error reading Excel file: {e}')
        traceback.print_exc()
        return {'data': []}
        
    finally:
        # Ensure workbook is always closed to prevent file-lock issues
        if wb is not None:
            try:
                wb.close()
            except Exception:
                pass
# TODO: Add Tools (if needed)



''' LLM '''
ocr_processing_llm = myChatOpenAI(
    temperature= 0.1
).with_structured_output(ReceiptData)

chat_llm = myChatOpenAI(
    temperature= 0.3
).bind_tools([
    tavily_search, currency_converter,
    read_excel, write_row_excel
])




''' Helpful Functions '''
def extract_receipt_data(image_input: Union[str, bytes]) -> dict:
    """
    Overview: Preprocesses a receipt image and runs PaddleOCR to extract raw text and potential fields.
    
    Caller Node: ocr_processing
    
    Instructions:
    1. Accept `image_input` which can be either a file path (str) or image data (bytes).
    2. If `image_input` is a path, load the image. If it's bytes, decode it into an image object.
    3. Preprocess the image (e.g., resize, grayscale, denoise) to improve OCR accuracy.
    4. Use PaddleOCR to extract raw text from the preprocessed image.
    5. Attempt to identify and extract key fields like total cost, date, items, location, and category from the raw OCR text.
    6. Return a dictionary containing the extracted fields. If a field cannot be confidently extracted, its value should be None.
    
    Args:
        image_input (Union[str, bytes]): The file path to the receipt image or the image data itself.
    
    Returns:
        dict: A dictionary with keys 'cost', 'date', 'items', 'location', 'category', where values are extracted strings or None if not found.
    """
    try:
        # Load image from path or bytes
        if isinstance(image_input, str):
            image = Image.open(image_input)
        elif isinstance(image_input, bytes):
            image = Image.open(BytesIO(image_input))
        else:
            raise ValueError("image_input must be either a file path (str) or image data (bytes)")
        
        # Preprocess image
        # Convert to grayscale
        image = image.convert('L')
        
        # Resize to max width of 1000px while maintaining aspect ratio
        width, height = image.size
        if width > 1000:
            ratio = 1000 / width
            new_height = int(height * ratio)
            image = image.resize((1000, new_height), Image.Resampling.LANCZOS)
        
        # Apply median filter for noise reduction
        image = image.filter(ImageFilter.MedianFilter(size=3))
        
        # Initialize PaddleOCR
        ocr = PaddleOCR(use_angle_cls=True, lang='en')#, show_log=False)
        
        # Convert PIL image to numpy array for PaddleOCR
        img_array = np.array(image)
        
        # Run OCR
        result = ocr.ocr(img_array)
        
        # Extract text lines from OCR result with robust checking
        lines = []
        if result and len(result) > 0 and result[0] is not None and len(result[0]) > 0:
            for line in result[0]:
                if line and line[1] and line[1][0]:
                    lines.append(line[1][0])
        
        # Initialize result dictionary
        extracted_data = {
            'cost': None,
            'date': None,
            'items': None,
            'location': None,
            'category': None
        }
        
        # If no text extracted, return empty result
        if not lines:
            return extracted_data
        
        # Extract location (first non-empty line)
        for line in lines:
            if line.strip():
                extracted_data['location'] = line.strip()
                break
        
        # Extract total cost - look for "total" in last few lines
        total_keywords = ['total', 'amount', 'sum', 'balance']
        for line in reversed(lines[-5:]):  # Check last 5 lines
            line_lower = line.lower()
            if any(keyword in line_lower for keyword in total_keywords):
                # Extract the last number in the line
                numbers = re.findall(r'\d+\.?\d*', line)
                if numbers:
                    try:
                        extracted_data['cost'] = float(numbers[-1])
                        break
                    except ValueError:
                        continue
        
        # If no total found with keywords, try to find the largest number in last few lines
        if extracted_data['cost'] is None:
            max_cost = 0.0
            for line in reversed(lines[-5:]):
                numbers = re.findall(r'\d+\.?\d*', line)
                for num in numbers:
                    try:
                        num_float = float(num)
                        if num_float > max_cost:
                            max_cost = num_float
                            extracted_data['cost'] = num_float
                    except ValueError:
                        continue
        
        # Extract date - look for common date formats
        date_patterns = [
            r'\d{4}-\d{2}-\d{2}',  # YYYY-MM-DD
            r'\d{2}/\d{2}/\d{4}',  # MM/DD/YYYY or DD/MM/YYYY
            r'\d{2}-\d{2}-\d{4}',  # MM-DD-YYYY or DD-MM-YYYY
            r'\d{2}\.\d{2}\.\d{4}',  # DD.MM.YYYY
        ]
        
        for line in lines:
            for pattern in date_patterns:
                match = re.search(pattern, line)
                if match:
                    extracted_data['date'] = match.group()
                    break
            if extracted_data['date']:
                break
        
        # Extract items - look for lines with quantity and price patterns
        formatted_items = []
        item_patterns = [
            (r'(\d+)\s*[xX]\s*(\d+\.?\d*)', 'qty_x_price'),  # quantity x price
            (r'(\d+)\s*@\s*(\d+\.?\d*)', 'qty_at_price'),  # quantity @ price
            (r'(\w+)\s+(\d+\.?\d*)', 'name_price'),  # item_name price
        ]
        
        for line in lines:
            line_stripped = line.strip()
            # Skip lines that are likely headers, totals, or dates
            if any(keyword in line_stripped.lower() for keyword in ['total', 'date', 'subtotal', 'tax']):
                continue
            if re.match(r'\d{4}-\d{2}-\d{2}', line_stripped):
                continue
            
            # Try to match item patterns and format them
            for pattern, pattern_type in item_patterns:
                match = re.search(pattern, line_stripped)
                if match:
                    if pattern_type == 'qty_x_price':
                        qty = match.group(1)
                        price = match.group(2)
                        # Try to extract item name from the line
                        item_name = re.sub(pattern, '', line_stripped).strip()
                        if not item_name:
                            item_name = 'Item'
                        formatted_items.append(f"{item_name} ({qty} x {price} EUR)")
                    elif pattern_type == 'qty_at_price':
                        qty = match.group(1)
                        price = match.group(2)
                        item_name = re.sub(pattern, '', line_stripped).strip()
                        if not item_name:
                            item_name = 'Item'
                        formatted_items.append(f"{item_name} ({qty} x {price} EUR)")
                    elif pattern_type == 'name_price':
                        item_name = match.group(1)
                        price = match.group(2)
                        formatted_items.append(f"{item_name} (1 x {price} EUR)")
                    break
        
        if formatted_items:
            extracted_data['items'] = ', '.join(formatted_items)
        
        # Infer category based on keywords
        category_keywords = {
            'Coffee': ['coffee', 'cafe', 'starbucks', 'espresso', 'latte', 'cappuccino'],
            'Groceries': ['grocery', 'supermarket', 'walmart', 'target', 'costco', 'food', 'market'],
            'Restaurant': ['restaurant', 'diner', 'bistro', 'grill', 'kitchen'],
            'Gas': ['gas', 'fuel', 'petrol', 'shell', 'bp', 'exxon'],
            'Pharmacy': ['pharmacy', 'drug', 'cvs', 'walgreens', 'prescription'],
            'Electronics': ['electronics', 'best buy', 'apple', 'computer', 'phone'],
            'Clothing': ['clothing', 'fashion', 'apparel', 'h&m', 'zara', 'nike'],
        }
        
        all_text = ' '.join(lines).lower()
        for category, keywords in category_keywords.items():
            if any(keyword in all_text for keyword in keywords):
                extracted_data['category'] = category
                break
        
        return extracted_data
        
    except Exception as e:
        print(f'{RED}[FUNCTION] [ERR]{RESET} Error in extract_receipt_data: {e}')
        traceback.print_exc()
        # Return empty result on error
        return {
            'cost': None,
            'date': None,
            'items': None,
            'location': None,
            'category': None
        }

def validate_ocr_result(ocr_data: dict) -> tuple[bool, str]:
    """
    Overview: Validates the completeness and confidence of the OCR-extracted receipt data.
    
    Caller Node: ocr_processing
    
    Instructions:
    1. Check if essential fields ('cost', 'date', 'items', 'location', 'category') are present and non-empty in the `ocr_data` dictionary.
    2. Validate the format of 'cost' (should be a number) and 'date' (should be YYYY-MM-DD format).
    3. Assess the overall confidence of the extracted data. This could involve checking for common OCR errors or missing critical information.
    4. Return a tuple: (True, 'Valid') if the data is considered valid and complete, otherwise (False, 'Reason for failure').
    
    Args:
        ocr_data (dict): A dictionary containing the raw OCR-extracted fields.
    
    Returns:
        tuple[bool, str]: A boolean indicating validity and a string describing the reason for invalidity if applicable.
    """
    # Define essential fields
    essential_fields = ['cost', 'date', 'items', 'location', 'category']
    
    # Check if ocr_data is None or not a dictionary
    if ocr_data is None or not isinstance(ocr_data, dict):
        return (False, 'OCR data is None or not a dictionary')
    
    # Check if all essential fields are present and non-empty
    for field in essential_fields:
        if field not in ocr_data:
            return (False, f'Missing essential field: {field}')
        
        value = ocr_data[field]
        
        # Check for None values
        if value is None:
            return (False, f'Field {field} is None')
        
        # Check for empty strings (for string fields)
        if isinstance(value, str) and value.strip() == '':
            return (False, f'Field {field} is empty')
    
    # Validate cost is a valid number
    cost = ocr_data.get('cost')
    if cost is not None:
        if not isinstance(cost, (int, float)):
            # Try to convert string to float if possible
            if isinstance(cost, str):
                try:
                    cost = float(cost)
                    # Update the dictionary with converted value
                    ocr_data['cost'] = cost
                except ValueError:
                    return (False, f'Field cost is not a valid number: {cost}')
            else:
                return (False, f'Field cost has invalid type: {type(cost).__name__}')
        
        # Check that cost is non-negative
        if cost < 0:
            return (False, f'Field cost is negative: {cost}')
    
    # Validate date format (YYYY-MM-DD) and that it's a real calendar date
    date = ocr_data.get('date')
    if date is not None and isinstance(date, str):
        date_pattern = r'^\d{4}-\d{2}-\d{2}$'
        if not re.match(date_pattern, date):
            return (False, f'Field date is not in YYYY-MM-DD format: {date}')
        
        # Validate that it's a real calendar date
        try:
            datetime.strptime(date, '%Y-%m-%d')
        except ValueError:
            return (False, f'Field date is not a valid calendar date: {date}')
    
    # All validations passed
    return (True, 'Valid')

def format_items(raw_items: list[dict]) -> str:
    """
    Overview: Converts a list of raw item dictionaries into the required formatted string for storage.
    
    Caller Node: ocr_processing
    
    Instructions:
    1. Iterate through the `raw_items` list, where each item is expected to be a dictionary with keys like 'name', 'quantity', 'price', and optionally 'currency'.
    2. For each item, format it as 'item_name (quantity x price currency)'. If currency is not provided, assume EUR.
    3. Join all formatted item strings with ', ' to create a single single string.
    4. Return the final formatted string.
    
    Args:
        raw_items (list[dict]): A list of dictionaries, each representing an item with its details.
    
    Returns:
        str: A formatted string of items, e.g., 'item1 (quantity x price currency), item2 (quantity x price currency)'.
    """
    # Handle empty list edge case
    if not raw_items:
        return ""
    
    formatted_items = []
    
    for item in raw_items:
        # Validate that item is a dictionary
        if not isinstance(item, dict):
            continue
        
        # Extract values with defaults, handling None values with 'or' operator
        name: str = item.get('name') or 'Item'
        
        # Coerce quantity to int with error handling
        try:
            quantity = int(item.get('quantity', 1))
        except (ValueError, TypeError):
            quantity = 1
        
        # Normalize price to float and format with 2 decimal places
        try:
            price_raw = item.get('price', 0.00)
            price = f"{float(price_raw):.2f}"
        except (ValueError, TypeError):
            price = "0.00"
        
        currency: str = item.get('currency') or 'EUR'
        
        # Format the item string
        formatted_item = f"{name} ({quantity} x {price} {currency})"
        formatted_items.append(formatted_item)
    
    # Join all formatted items with ', '
    return ', '.join(formatted_items)
# TODO: Add Helpful Functions (if needed)



''' Nodes '''
def ocr_processing(state: AgentSchema) -> AgentSchema:
    """ Execution: LLM+TOOLS. Processes receipt photos using OCR (OpenRouter or PaddleOCR) to extract cost, date, items, location, and category. If OCR fails or receipt is unclear, sets state.mode to 'ocr_failed' and transitions to chat to notify user. On success, writes extracted data to the local Excel file using excel_io tool and transitions to chat for confirmation reply. 
    Processes receipt photos using OCR to extract structured data (cost, date, items, location, category) and transitions to chat for confirmation or error handling. This node is triggered when a receipt photo is detected in the incoming message.
    
    Steps:
    1. Check if the last message contains a receipt photo (via state.mode or message content).
    2. If yes, invoke OCR using OpenRouter or PaddleOCR to extract fields.
    3. Validate extracted data; if invalid or low confidence, set state.mode to 'ocr_failed'.
    4. If valid, format items as 'item1 (quantity x price currency), ...' and set state.next_action to 'confirm_receipt'.
    5. Transition to chat node for user reply.
    
    Inputs:
    - state.messages: List of conversation messages; last message may contain image.
    - state.mode: Indicates if processing a receipt (e.g., 'process_receipt').
    - state.last_seen_event_id: To avoid reprocessing duplicates.
    
    Outputs:
    - Updated state with extracted receipt data in messages or error state.
    - state.next_action: Set to 'confirm_receipt' or 'ocr_failed'.
    - Appends OCR result or error message to messages.
    
    Helpful Functions:
    - extract_receipt_data: Preprocess image and run OCR.
    - validate_ocr_result: Check confidence and completeness.
    - format_items: Convert raw items to required string format.
    
    Note: Uses ToolNode for tool execution; LLM may call tools during processing.
    """

    print_function_name()
    try:
        # Get the last message to check for image content
        last_message = state['messages'][-1]
        
        # Extract image content from the last message
        image_content = None
        if hasattr(last_message, 'content') and isinstance(last_message.content, list):
            # Handle multi-modal content (list of content blocks)
            for content_block in last_message.content:
                if isinstance(content_block, dict) and content_block.get('type') == 'image_url':
                    image_url = content_block['image_url']['url']
                    # Download image from URL if it's a URL, otherwise use as file path
                    if image_url.startswith('http://') or image_url.startswith('https://'):
                        
                        response = requests.get(image_url, timeout=10)
                        image_content = response.content
                    else:
                        image_content = image_url
                    break
        elif hasattr(last_message, 'content') and isinstance(last_message.content, (str, bytes)):
            # Handle raw string (file path) or bytes content
            image_content = last_message.content
        
        # If no image content found, try to extract from message additional_kwargs
        if image_content is None and hasattr(last_message, 'additional_kwargs'):
            image_content = last_message.additional_kwargs.get('image', None)
        
        # Check if we have image content to process
        if image_content is None:
            return {
                'mode': 'ocr_failed',
                'next_action': 'ocr_failed',
                'messages': [AIMessage(content="No receipt image found in the message. Please send a clear photo of your receipt.")],
                'latest': "No receipt image found in the message. Please send a clear photo of your receipt."
            }
        
        # Use extract_receipt_data helper function to extract raw OCR data
        raw_ocr_data = extract_receipt_data(image_content)
        
        # Validate the extracted OCR data
        is_valid, validation_message = validate_ocr_result(raw_ocr_data)
        
        if not is_valid:
            # OCR validation failed
            return {
                'mode': 'ocr_failed',
                'next_action': 'ocr_failed',
                'messages': [AIMessage(content=f"OCR processing failed: {validation_message}. Please provide a clearer receipt image or enter the details manually.")],
                'latest': f"OCR processing failed: {validation_message}. Please provide a clearer receipt image or enter the details manually."
            }
        
        # Format the OCR processing prompt with extracted data for LLM refinement
        prompt = prompts.OCR_PROCESSING_PROMPT.format(
            extracted_data=json.dumps(raw_ocr_data, indent=2),
            mode=state.get('mode', 'unknown')
        )
        
        # Prepare messages for the LLM
        messages = [
            SystemMessage(content=prompt),
            last_message
        ]
        
        # Invoke the OCR processing LLM with structured output to refine the extracted data
        result = safe_invoke(ocr_processing_llm, messages=messages)
        
        # Extract the structured ReceiptData from the result
        if isinstance(result, AIMessage):
            receipt_data = result.content
        else:
            receipt_data = result
        
        # If LLM returns None or invalid result, use the raw OCR data
        if receipt_data is None:
            # Try to create ReceiptData from raw_ocr_data
            try:
                # Format items using the helper function if items is a list
                items = raw_ocr_data.get('items')
                if isinstance(items, list):
                    items = format_items(items)
                
                receipt_data = ReceiptData(
                    cost=raw_ocr_data.get('cost', 0.0),
                    date=raw_ocr_data.get('date', ''),
                    items=items or '',
                    location=raw_ocr_data.get('location', ''),
                    category=raw_ocr_data.get('category', '')
                )
            except Exception as e:
                return {
                    'mode': 'ocr_failed',
                    'next_action': 'ocr_failed',
                    'messages': [AIMessage(content=f"Failed to process receipt data: {str(e)}. Please try again with a clearer image.")],
                    'latest': f"Failed to process receipt data: {str(e)}. Please try again with a clearer image."
                }
        
        # Convert ReceiptData to dict for final validation and formatting
        if isinstance(receipt_data, ReceiptData):
            ocr_data_dict = {
                'cost': receipt_data.cost,
                'date': receipt_data.date,
                'items': receipt_data.items,
                'location': receipt_data.location,
                'category': receipt_data.category
            }
        else:
            ocr_data_dict = receipt_data
            # Format items if it's a list
            if isinstance(ocr_data_dict.get('items'), list):
                ocr_data_dict['items'] = format_items(ocr_data_dict['items'])
        
        # Final validation after LLM processing
        is_valid_final, validation_message_final = validate_ocr_result(ocr_data_dict)
        
        if not is_valid_final:
            return {
                'mode': 'ocr_failed',
                'next_action': 'ocr_failed',
                'messages': [AIMessage(content=f"OCR processing failed after refinement: {validation_message_final}. Please provide a clearer receipt image.")],
                'latest': f"OCR processing failed after refinement: {validation_message_final}. Please provide a clearer receipt image."
            }
        
        # OCR validation succeeded - prepare success response
        formatted_message = (
            f"Receipt processed successfully!\n\n"
            f"Location: {ocr_data_dict['location']}\n"
            f"Date: {ocr_data_dict['date']}\n"
            f"Total Cost: {ocr_data_dict['cost']}\n"
            f"Items: {ocr_data_dict['items']}\n"
            f"Category: {ocr_data_dict['category']}\n\n"
            f"Is this information correct?"
        )
        
        latest_message = (
            f"Receipt processed successfully! Location: {ocr_data_dict['location']}, "
            f"Date: {ocr_data_dict['date']}, Total Cost: {ocr_data_dict['cost']}, "
            f"Category: {ocr_data_dict['category']}. Is this information correct?"
        )
        
        return {
            'next_action': 'confirm_receipt',
            'receipt_data': receipt_data if isinstance(receipt_data, ReceiptData) else ReceiptData(**ocr_data_dict),
            'messages': [AIMessage(content=formatted_message)],
            'latest': latest_message
        }
        
    except Exception as e:
        print(f'{RED}[NODE] [ERR]{RESET}', e) if DEBUG else None
        traceback.print_exc() if DEBUG else None
        
        # Handle exceptions by returning error state
        return {
            'mode': 'ocr_failed',
            'next_action': 'ocr_failed',
            'messages': [AIMessage(content=f"An error occurred while processing the receipt: {str(e)}. Please try again with a clearer image.")],
            'latest': f"An error occurred while processing the receipt: {str(e)}. Please try again with a clearer image."
        }


def chat(state: AgentSchema) -> AgentSchema:
    """ Execution: LLM+TOOLS. Main conversational agent that generates user-facing replies. Uses tools: tavily_search (for context if needed), excel_io (read/write local Excel file), currency_converter (static rates for EUR conversion). Handles two main cases: 1) After OCR processing, confirms receipt data was saved or notifies user of OCR failure. 2) Responds to spending queries by retrieving data from local Excel file and calculating answers. All replies are sent via external Green-API integration. 
    Main conversational agent that generates user-facing replies. Handles two cases: confirming receipt data after OCR, or answering spending queries from Excel. Uses tools for search, Excel I/O, and currency conversion. All replies are sent via external Green-API.
    
    Steps:
    1. Read state.messages and state.next_action to determine context.
    2. If next_action is 'confirm_receipt', generate confirmation message with extracted data.
    3. If next_action is 'ocr_failed', notify user and ask for clarification.
    4. If user query (e.g., 'how much spent on groceries?'), use excel_io to read data and calculate answer.
    5. For ambiguous queries, use tavily_search for context if needed.
    6. Format reply in English, using Euro as primary currency.
    7. Append reply to messages as AIMessage.
    8. Set state.next_action if follow-up needed, else clear it.
    9. Transition to END.
    
    Inputs:
    - state.messages: Conversation history, including last user message.
    - state.next_action: Indicates context (e.g., 'confirm_receipt', 'ocr_failed', or query type).
    - state.pending_question: If clarification is needed.
    
    Outputs:
    - state.messages: Appended with assistant reply.
    - state.next_action: Updated or cleared based on response.
    - state.latest: The generated reply text.
    
    Tools:
    - tavily_search: For external context if query is ambiguous.
    - excel_io: To read/write local Excel file for spending data.
    - currency_converter: Static rates for EUR conversion.
    
    Helpful Functions:
    - parse_spending_query: Extract category, time period from user question.
    - calculate_spending: Sum costs from Excel based on filters.
    - format_reply: Construct natural language response.
    
    Note: This node may use ToolNode for tool calls; ensure tools are bound to LLM.
    """

    print_function_name()
    try:
        # Extract state variables
        next_action: str = state.get('next_action', '')
        receipt_data: Optional[ReceiptData] = state.get('receipt_data', None)
        pending_question: str = state.get('pending_question', '')
        
        # Convert receipt_data to dict safely if it's a Pydantic model
        receipt_data_dict = None
        if receipt_data is not None:
            if isinstance(receipt_data, ReceiptData):
                receipt_data_dict = {
                    'cost': receipt_data.cost,
                    'date': receipt_data.date,
                    'items': receipt_data.items,
                    'location': receipt_data.location,
                    'category': receipt_data.category
                }
            elif isinstance(receipt_data, dict):
                receipt_data_dict = receipt_data
        
        # Prepare context for the prompt based on next_action
        context_info = ''
        if next_action == 'confirm_receipt' and receipt_data_dict:
            context_info = f"""
Receipt Data Extracted:
- Location: {receipt_data_dict.get('location', 'Unknown')}
- Date: {receipt_data_dict.get('date', 'Unknown')}
- Total Cost: {receipt_data_dict.get('cost', 0)} EUR
- Items: {receipt_data_dict.get('items', 'Unknown')}
- Category: {receipt_data_dict.get('category', 'Unknown')}

The user needs to confirm if this data is correct. Ask for confirmation and let them know the data will be saved to the Excel file.
"""
        elif next_action == 'ocr_failed':
            context_info = """
OCR processing failed. The receipt image could not be processed properly. 
Ask the user to:
1. Send a clearer photo of the receipt
2. Or manually enter the receipt details
"""
        elif next_action == 'query_spending' or pending_question:
            context_info = """
The user is asking about their spending. Use the read_excel tool to retrieve data from the Excel file.
Calculate the answer based on their query (e.g., total spent on groceries, spending in a specific month, etc.).
"""
        else:
            context_info = """
General conversation mode. Respond helpfully to the user's message.
If they ask about spending, use read_excel to get data.
If they need external information, use tavily_search.
"""
        
        # Format the system prompt with context
        prompt = prompts.CHAT_PROMPT.format(
            context=context_info,
            next_action=next_action,
            pending_question=pending_question
        )
        
        # Prepare messages for the LLM - only pass system prompt, not full history
        # The conversation history is already in state['messages'] and will be handled by LangGraph
        messages = [SystemMessage(content=prompt)] + state.get('messages', [])
        
        # Invoke the chat LLM (which has tools bound to it)
        result: AIMessage = safe_invoke(chat_llm, messages=messages)
        
        # Extract the reply text from the result
        reply: str = result.content if result.content else ""
        
        # Clear next_action - set to empty string to stay consistent with str type
        new_next_action: str = ""
        
        # Return updated state with the full AIMessage to preserve tool_calls
        # This allows from_chat_to to properly route to chat_tools_all when tools are called
        return {
            'messages': [result],
            'next_action': new_next_action,
            'latest': reply
        }
        
    except Exception as e:
        print(f'{RED}[NODE] [ERR]{RESET}', e) if DEBUG else None
        traceback.print_exc() if DEBUG else None
        
        # Return error state with helpful message, preserving existing messages
        error_message: str = "I apologize, but I encountered an error processing your request. Please try again or rephrase your question."
        return {
            'messages': state.get('messages', []) + [AIMessage(content=error_message)],
            'next_action': "",
            'latest': error_message
        }



''' Conditional Functions '''
def from_start_to(state: AgentSchema) -> Literal["ocr_processing", "chat"]:
    """
    Routes to ocr_processing if the agent is in receipt processing mode; otherwise routes to chat for general conversation or spending queries.
    """
    print_function_name()
    # TODO: <conditions>
    if state.get("mode") == "process_receipt":
        return "ocr_processing"
    return "chat"


def from_chat_to(state: AgentSchema) -> Literal["chat_tools_all", "__end__"]:
    """
    Routes to tool execution if the last AI message contains tool calls; otherwise routes to end.
    """
    print_function_name() if DEBUG else None
    if will_tool_call(state['messages']):
        return "chat_tools_all"
    return "__end__"



''' Graph '''
whatsapp_receipt_agent_graph = StateGraph(AgentSchema)

whatsapp_receipt_agent_graph.add_node("ocr_processing", ocr_processing)
whatsapp_receipt_agent_graph.add_node("chat", chat)
whatsapp_receipt_agent_graph.add_node("chat_tools_all", ToolNode([tavily_search, read_excel, write_row_excel, currency_converter]))

whatsapp_receipt_agent_graph.add_conditional_edges(
    "__start__",
    from_start_to,
    {   # Not needed just for clarity
        "ocr_processing": "ocr_processing",
        "chat": "chat",
    }
)
whatsapp_receipt_agent_graph.add_edge("ocr_processing", "chat")
whatsapp_receipt_agent_graph.add_conditional_edges(
    "chat",
    from_chat_to,
    {
        "chat_tools_all": "chat_tools_all",
        "__end__": END,
    }
)
whatsapp_receipt_agent_graph.add_edge("chat_tools_all", "chat")


whatsapp_receipt_agent_app = whatsapp_receipt_agent_graph.compile(checkpointer= MemorySaver())



''' Testing '''
if __name__ == '__main__':
    from IPython.display import Image as GraphImage

    # Visualize the graph
    GraphImage(whatsapp_receipt_agent_app.get_graph().draw_mermaid_png(max_retries= 5, retry_delay= 2.0))
    parent_dir = Path(__file__).resolve().parent
    if not os.path.exists(parent_dir / 'graphs'):
        os.makedirs(parent_dir / 'graphs')
    with open(parent_dir / 'graphs/whatsapp_receipt_agent_app.png', 'wb') as f:
        f.write(whatsapp_receipt_agent_app.get_graph().draw_mermaid_png())

    
    # Connect to langsmith
    from langsmith import Client
    os.environ['LANGCHAIN_PROJECT'] = 'whatsapp_receipt_agent'
    os.environ['LANGSMITH_PROJECT'] = 'whatsapp_receipt_agent'
    client = Client()

    config = {
        'recursion_limit': 100,
        'configurable': {
            'user_id': 'whatsapp_receipt_agent',
            'run_name': 'whatsapp_receipt_agent',
            'thread_id': 'whatsapp_receipt_agent', 
        }
    }

    user_in = input(f'{GREEN}[USER INPUT]{RESET} > ')
    while user_in.lower() != 'q':
        if user_in.startswith('re:'): # receipt
            user_in = user_in[3:]
            response = whatsapp_receipt_agent_app.invoke({'messages': [HumanMessage(content=user_in)], 'mode': 'process_receipt'}, config= config)
            print(f'{BLUE}[MAIN] [INFO]{RESET} {response["latest"]}') if DEBUG else None
            user_in = input(f'{GREEN}[USER INPUT]{RESET} > ')

        else:
            response = whatsapp_receipt_agent_app.invoke({'messages': [HumanMessage(content=user_in)]}, config= config)
            print(f'{BLUE}[MAIN] [INFO]{RESET} {response["latest"]}') if DEBUG else None
            user_in = input(f'{GREEN}[USER INPUT]{RESET} > ')

    print(f'{BLUE}[MAIN] [INFO]{RESET} Response') if DEBUG else None
    if DEBUG:
        for key, value in response.items():
            print(f'    {key}: {value}')

    # pip uninstall Image paddleocr openpyxl