''' Imports '''
# Langchain imports
from langchain_core.messages import SystemMessage, AIMessage, BaseMessage, ToolMessage, HumanMessage
from langchain_core.tools import tool

# Langgraph imports
from langgraph.graph import StateGraph, MessagesState
from langgraph.checkpoint.memory import MemorySaver
from langgraph.constants import END, START
from langgraph.prebuilt import ToolNode

# Schema imports
from typing import TypedDict, Literal, List, Optional, Annotated, Union, Dict, Any
from pydantic import BaseModel, Field
from operator import add

# General imports
from dotenv import load_dotenv
from pathlib import Path
from time import sleep
import traceback
import json
import os

# My imports
from utils.utils import myChatOpenAI, safe_invoke, print_function_name, will_tool_call, parse_tool_arguments, USER_APPROVALS, read_state_file, clean_llm_output
from creations.problem_solution_pipeline import problem_solution_pipeline_prompts as prompts

import shutil
import subprocess
import tempfile
import uuid



''' Constants '''
load_dotenv(dotenv_path= Path(__file__).resolve().parent.parent.parent / '.env')

DEBUG = os.getenv('DEBUG')

BLUE = '\033[94m' # INFO
RED = '\033[91m' # ERR
GREEN = '\033[92m' # REST
RESET = '\033[0m'



print(f'\n{BLUE}[AGENT] [INFO] [STARTUP]{RESET} problem_solution_pipeline') if DEBUG else None



""" Schemas """

class TestResultEntry(TypedDict):
	"""
	Represents a single test result entry for a sample. Captures whether the sample passed all test cases, optional error message, number of tests passed, and total number of tests. Used as the value type in the test_results dictionary within AgentSchema.
	"""
	passed: bool # True if the sample passed all test cases, otherwise False.
	error: Optional[str] # Optional error message when passed is False; provides details about the failure.
	number_tests_passed: int # Number of test cases that passed for this sample.
	total_tests: int # Total number of test cases for this sample.

class AgentSchema(TypedDict):
	"""
	Main state schema for the problem_solution_pipeline graph. It aggregates all keys used across nodes: problem specification (function_signature, docstring, test_cases, optional task_id), generation artifacts (samples, generation_attempt), validation artifacts (valid_samples, invalid_samples, syntax_validation_passed), test execution results (test_results, total_passed, total_failed), repair tracking (repair_round, repair_feedback, should_repair), and final output (final_solution). This TypedDict serves as the unified state object for the LangGraph workflow.
	"""
	function_signature: str # <- Target function signature from the problem spec; used by generate_samples and finalize_solution.
	docstring: str # <- NaturalÃ¢â‚¬â€˜language description of required behavior; used by generate_samples and finalize_solution.
	test_cases: List[Any] # <- List of test cases defining expected inputs/outputs; consumed by generate_samples, execute_tests, and finalize_solution.
	task_id: Optional[str] # <- Optional identifier for the problem (metadata); passed through to finalize_solution for solution_metadata.
	samples: List[str] # Raw code strings generated by the LLM; produced by generate_samples and consumed by validate_syntax, execute_tests, repair_samples, and finalize_solution.
	generation_attempt: int # Counter tracking how many times generation has been performed; used in generate_samples to monitor progress.
	valid_samples: List[str] # Samples that passed syntax validation; output of validate_syntax and input to execute_tests.
	invalid_samples: List[str] # Samples that raised SyntaxError; output of validate_syntax (kept for debugging).
	syntax_validation_passed: bool # Flag indicating whether any syntactically valid samples remain; used to decide if testing should proceed.
	test_results: Dict[int, TestResultEntry] # Mapping from sample index to its test outcome (passed flag, optional error, number_tests_passed, total_tests); produced by execute_tests and consumed by analyze_failures and repair_samples.
	total_passed: int # Number of samples that passed all tests; computed in execute_tests and used in analyze_failures.
	total_failed: int # Number of samples that failed at least one test; computed in execute_tests and used in analyze_failures.
	repair_round: int # Current repair round count (default 0); incremented in repair_samples and tracked in analyze_failures to enforce the 2Ã¢â‚¬â€˜round limit.
	repair_feedback: str # Guidance generated by analyze_failures_llm on how to fix failing samples; consumed by repair_samples.
	should_repair: bool # Flag indicating whether a repair step should be triggered; set by analyze_failures and used for conditional routing.
	final_solution: str # Complete Python function code assembled by finalize_solution; the ultimate output of the pipeline.


''' Tools '''

# TODO: Add Tools (if needed)



''' LLM '''
generate_samples_llm = myChatOpenAI(
	temperature= 0.6
)
analyze_failures_llm = myChatOpenAI(
	temperature= 0.2
)
repair_samples_llm = myChatOpenAI(
	temperature= 0.6
)



''' Helpful Functions '''
def validate_code_syntax(code: str) -> bool:
	"""
	Overview: Checks if a given Python code string is syntactically valid using ast.parse.
	Caller Node: validate_syntax
	
	Instructions: Retrieve the code string, attempt to parse it with ast.parse, catch SyntaxError, return True if parsing succeeds, False otherwise.
	
	Args: code (str): The Python source code to validate.
	
	Returns: bool: True if syntax is valid, False otherwise.
	"""
	...


def run_code_in_isolated_sandbox(
    code: str,
    test_cases: list,
    function_signature: str,
    *,
    timeout_seconds: int = 8,
    memory_limit: str = "256m",
    cpus: str = "1.0",
    pids_limit: int = 64,
    docker_image: str = "python:3.11-slim",
) -> dict:
    """
    Executes generated Python code inside a locked-down Docker container.

    Supports test cases:
    1. "assert add(1, 2) == 3"
    2. {"inputs": [1, 2], "expected": 3}
    3. {"input": [1, 2, 3], "expected": 6}
    4. [[1, 2], 3]  # legacy tuple/list style

    Returns:
    {
        "passed": bool,
        "error": str | None,
        "number_tests_passed": int,
        "total_tests": int,
        "test_results": list
    }
    """
    total_tests = len(test_cases)

    if shutil.which("docker") is None:
        return {
            "passed": False,
            "error": "Docker is not installed or not available on PATH.",
            "number_tests_passed": 0,
            "total_tests": total_tests,
            "test_results": [],
        }

    try:
        payload_json = json.dumps(
            {
                "code": code,
                "test_cases": test_cases,
                "function_signature": function_signature,
            },
            ensure_ascii=False,
        )
    except TypeError as exc:
        return {
            "passed": False,
            "error": f"test_cases must be JSON-serializable: {exc}",
            "number_tests_passed": 0,
            "total_tests": total_tests,
            "test_results": [],
        }

    runner_code = r'''
import ast
import json
import os
import sys


original_stdout_fd = os.dup(1)


def safe_emit(payload):
    try:
        data = json.dumps(payload, ensure_ascii=False)
    except Exception as exc:
        data = json.dumps({
            "passed": False,
            "error": f"Could not serialize sandbox result: {exc}",
            "number_tests_passed": 0,
            "total_tests": 0,
            "test_results": [],
        })

    os.write(original_stdout_fd, data.encode("utf-8") + b"\n")


try:
    devnull_fd = os.open(os.devnull, os.O_WRONLY)
    os.dup2(devnull_fd, 1)
    os.dup2(devnull_fd, 2)
    sys.stdout = open(os.devnull, "w", encoding="utf-8")
    sys.stderr = open(os.devnull, "w", encoding="utf-8")

    with open("/sandbox/payload.json", "r", encoding="utf-8") as f:
        payload = json.load(f)

    code = payload["code"]
    test_cases = payload["test_cases"]
    function_signature = payload["function_signature"]
    total_tests = len(test_cases)

    namespace = {
        "__name__": "__submitted_solution__",
    }

    try:
        compiled_code = compile(code, "/sandbox/submitted_solution.py", "exec")
        exec(compiled_code, namespace)
    except BaseException as exc:
        safe_emit({
            "passed": False,
            "error": f"Code execution failed: {type(exc).__name__}: {exc}",
            "number_tests_passed": 0,
            "total_tests": total_tests,
            "test_results": [],
        })
        raise SystemExit(0)

    try:
        signature = function_signature.strip()

        if signature.isidentifier():
            function_name = signature
        else:
            try:
                tree = ast.parse(signature)
            except SyntaxError:
                if signature.startswith("def ") and signature.endswith(":"):
                    tree = ast.parse(signature + "\n    pass")
                else:
                    raise

            first_node = tree.body[0]

            if isinstance(first_node, ast.FunctionDef):
                function_name = first_node.name
            elif isinstance(first_node, ast.Expr):
                expression = first_node.value

                if isinstance(expression, ast.Name):
                    function_name = expression.id
                elif isinstance(expression, ast.Call) and isinstance(expression.func, ast.Name):
                    function_name = expression.func.id
                else:
                    raise ValueError("Could not extract function name.")
            else:
                raise ValueError("Could not extract function name.")

        target_function = namespace.get(function_name)

        if target_function is None or not callable(target_function):
            raise ValueError(f"Function '{function_name}' not found or not callable.")

    except BaseException as exc:
        safe_emit({
            "passed": False,
            "error": f"Failed to extract function: {type(exc).__name__}: {exc}",
            "number_tests_passed": 0,
            "total_tests": total_tests,
            "test_results": [],
        })
        raise SystemExit(0)

    passed_tests = 0
    error_messages = []
    test_results = []

    for index, test_case in enumerate(test_cases, start=1):
        try:
            if isinstance(test_case, str):
                stripped = test_case.strip()

                if not stripped.startswith("assert") and "check(" not in stripped:
                    raise ValueError(
                        "String test cases must be assert statements "
                        "or HumanEval-style check(candidate) tests."
                    )

                test_namespace = dict(namespace)
                test_namespace["candidate"] = target_function
                test_namespace[function_name] = target_function

                compiled_test = compile(
                    test_case,
                    f"/sandbox/test_{index}.py",
                    "exec",
                )

                exec(compiled_test, test_namespace)

                passed_tests += 1
                test_results.append({
                    "test": index,
                    "passed": True,
                    "error": None,
                })

            else:
                if isinstance(test_case, dict):
                    if "expected" not in test_case:
                        raise ValueError("Dict test case must contain 'expected'.")

                    expected = test_case["expected"]

                    if "inputs" in test_case:
                        inputs = test_case["inputs"]

                        if not isinstance(inputs, list):
                            raise ValueError("'inputs' must be a list.")

                        result = target_function(*inputs)

                    elif "input" in test_case:
                        result = target_function(test_case["input"])

                    else:
                        raise ValueError("Dict test case must contain 'input' or 'inputs'.")

                elif isinstance(test_case, list) and len(test_case) == 2:
                    inputs, expected = test_case

                    if isinstance(inputs, list):
                        result = target_function(*inputs)
                    else:
                        result = target_function(inputs)

                else:
                    raise ValueError(f"Invalid test case format: {test_case!r}")

                if result == expected:
                    passed_tests += 1
                    test_results.append({
                        "test": index,
                        "passed": True,
                        "error": None,
                    })
                else:
                    message = f"Expected {expected!r}, got {result!r}"
                    error_messages.append(f"Test {index}: {message}")
                    test_results.append({
                        "test": index,
                        "passed": False,
                        "error": message,
                    })

        except AssertionError as exc:
            message = str(exc) or "Assertion failed"
            error_messages.append(f"Test {index}: {message}")
            test_results.append({
                "test": index,
                "passed": False,
                "error": message,
            })

        except BaseException as exc:
            message = f"{type(exc).__name__}: {exc}"
            error_messages.append(f"Test {index}: {message}")
            test_results.append({
                "test": index,
                "passed": False,
                "error": message,
            })

    safe_emit({
        "passed": len(error_messages) == 0,
        "error": "\n".join(error_messages) if error_messages else None,
        "number_tests_passed": passed_tests,
        "total_tests": total_tests,
        "test_results": test_results,
    })

except BaseException as exc:
    safe_emit({
        "passed": False,
        "error": f"Sandbox runner crashed: {type(exc).__name__}: {exc}",
        "number_tests_passed": 0,
        "total_tests": 0,
        "test_results": [],
    })
'''

    container_name = f"code-sandbox-{uuid.uuid4().hex}"

    with tempfile.TemporaryDirectory(prefix="code_sandbox_") as temp_dir:
        temp_path = Path(temp_dir)

        runner_path = temp_path / "runner.py"
        payload_path = temp_path / "payload.json"

        runner_path.write_text(runner_code, encoding="utf-8")
        payload_path.write_text(payload_json, encoding="utf-8")

        try:
            os.chmod(temp_path, 0o755)
            os.chmod(runner_path, 0o644)
            os.chmod(payload_path, 0o644)
        except OSError:
            pass

        docker_command = [
            "docker",
            "run",
            "--rm",
            "--name",
            container_name,

            # No network.
            "--network",
            "none",

            # Resource limits.
            "--memory",
            memory_limit,
            "--memory-swap",
            memory_limit,
            "--cpus",
            cpus,
            "--pids-limit",
            str(pids_limit),

            # Lower privileges.
            "--cap-drop",
            "ALL",
            "--security-opt",
            "no-new-privileges:true",
            "--user",
            "65534:65534",

            # Read-only container filesystem.
            "--read-only",

            # Small writable temp area.
            "--tmpfs",
            "/tmp:rw,noexec,nosuid,size=64m",

            # Mount only runner and payload.
            "--mount",
            f"type=bind,source={str(temp_path.resolve())},target=/sandbox,readonly",

            "--workdir",
            "/sandbox",

            "-e",
            "PYTHONDONTWRITEBYTECODE=1",
            "-e",
            "HOME=/tmp",

            docker_image,
            "python",
            "/sandbox/runner.py",
        ]

        try:
            process = subprocess.Popen(
                docker_command,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            stdout, stderr = process.communicate(timeout=timeout_seconds)

        except subprocess.TimeoutExpired:
            try:
                subprocess.run(
                    ["docker", "rm", "-f", container_name],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    timeout=3,
                )
            except Exception:
                pass

            return {
                "passed": False,
                "error": f"Sandbox timeout after {timeout_seconds} seconds.",
                "number_tests_passed": 0,
                "total_tests": total_tests,
                "test_results": [],
            }

        except Exception as exc:
            return {
                "passed": False,
                "error": f"Failed to start Docker sandbox: {type(exc).__name__}: {exc}",
                "number_tests_passed": 0,
                "total_tests": total_tests,
                "test_results": [],
            }

        stdout = (stdout or "").strip()
        stderr = (stderr or "").strip()

        if not stdout:
            return {
                "passed": False,
                "error": (
                    f"Sandbox produced no result. Exit code: {process.returncode}."
                    + (f"\nStderr: {stderr[:2000]}" if stderr else "")
                ),
                "number_tests_passed": 0,
                "total_tests": total_tests,
                "test_results": [],
            }

        try:
            return json.loads(stdout.splitlines()[-1])
        except Exception:
            return {
                "passed": False,
                "error": (
                    "Sandbox did not return valid JSON."
                    f"\nExit code: {process.returncode}"
                    f"\nStdout: {stdout[:2000]}"
                    f"\nStderr: {stderr[:2000]}"
                ),
                "number_tests_passed": 0,
                "total_tests": total_tests,
                "test_results": [],
            }
# TODO: Add Helpful Functions (if needed)



''' Nodes '''
def generate_samples(state: AgentSchema) -> AgentSchema:
    """ Execution: LLM. Generates multiple Python code samples from the parsed problem specification using the LLM. Stores generated samples in state and routes to validate_syntax. 
	Execution: LLM. Generates multiple Python code samples from the parsed problem specification using the LLM. Stores generated samples in state and routes to validate_syntax.
	
	Overview:
	    This node reads the problem specification (function_signature, docstring, test_cases, optional task_id) from the workflow state and uses the generate_samples_llm to produce several candidate implementations. The generated code snippets are stored back into the state so that subsequent nodes can validate them for syntax and functionality.
	
	StepÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬ËœbyÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœstep:
	    1. Extract the specification fields from state: function_signature, docstring, test_cases, and optionally task_id.
	    2. Build a prompt that includes the signature, docstring, and test cases, asking the LLM for N code samples (e.g., 5).
	    3. Invoke generate_samples_llm with the prompt (system message) and capture the raw response.
	    4. Parse the response into a list of code strings (e.g., by stripping markdown fences or using a structured format).
	    5. Store the list under the key "samples" in the state.
	    6. Optionally set a counter "generation_attempt" to track how many times generation has been performed.
	    7. Route to validate_syntax.
	
	Inputs:
	    - function_signature (str): Target function signature from the problem spec.
	    - docstring (str): NaturalÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœlanguage description of required behavior.
	    - test_cases (list): Test cases defining expected inputs/outputs.
	    - task_id (optional, str): Identifier for the problem (metadata).
	
	Outputs:
	    - samples (list of str): Raw code strings generated by the LLM.
	    - generation_attempt (int): Current generation round counter.
	
	Possible tools:
	    - None (the LLM itself performs the generation). No ToolNode is required.
	
	Possible helpful functions:
	    - None (prompt creation, parsing, and formatting are excluded per guidelines).
	"""

    print_function_name()
    try:
        # TODO: <preprocess>
        ... # TODO: <make format arguments readable>
        prompt = prompts.GENERATE_SAMPLES_PROMPT.format(...) # TODO: <formatting>
        result = safe_invoke(generate_samples_llm, messages= [SystemMessage(content= prompt), ...]) # TODO: <inputs>
        # TODO: <postprocess>
        return ... # TODO: <return>
    except Exception as e:
        print(f'{RED}[NODE] [ERR]{RESET}', e) if DEBUG else None
        traceback.print_exc() if DEBUG else None
        # TODO: <error_handling> if needed
        return state


def validate_syntax(state: AgentSchema) -> AgentSchema:
    """ Execution: CODE. Validates each generated sample using Python's AST module for syntax correctness. Marks samples as valid/invalid and retains only valid ones for testing. Routes to execute_tests. 
	Execution: CODE. Validates each generated sample using Python's AST module for syntax correctness. Marks samples as valid/invalid and retains only valid ones for testing. Routes to execute_tests.
	
	Overview:
	    This node ensures that every candidate implementation is syntactically correct Python. It uses the ast module to parse each sample; successful parses are kept for functional testing, while invalid samples are recorded separately.
	
	StepÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬ËœbyÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœstep:
	    1. Retrieve the list of samples from state under the key "samples".
	    2. Initialise empty lists valid_samples and invalid_samples.
	    3. For each sample:
	        a. Attempt ast.parse(sample).
	        b. If parsing succeeds, add the sample to valid_samples.
	        c. If a SyntaxError occurs, add the sample to invalid_samples and optionally capture the error message.
	    4. Update state with valid_samples (key "valid_samples") and invalid_samples (key "invalid_samples").
	    5. Set a flag "syntax_validation_passed" to True if valid_samples is nonÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœempty.
	    6. Route to execute_tests.
	
	Inputs:
	    - samples (list of str): Raw code strings to validate.
	
	Outputs:
	    - valid_samples (list of str): Samples that passed syntax validation.
	    - invalid_samples (list of str): Samples that raised SyntaxError.
	    - syntax_validation_passed (bool): Indicator whether any valid samples remain.
	
	Possible tools:
	    - None (pure Python code). No ToolNode needed.
	
	Possible helpful functions:
	    - validate_code_syntax(code: str) -> bool: Returns True if ast.parse succeeds, otherwise False.
	"""

    print_function_name()
    try:
        # TODO: <process>
        return ... # TODO: <return>
    except Exception as e:
        print(f'{RED}[NODE] [ERR]{RESET}', e) if DEBUG else None
        traceback.print_exc() if DEBUG else None
        # TODO: <error_handling> if needed
        return state


def execute_tests(state: AgentSchema) -> AgentSchema:
    """ Execution: CODE. Runs each syntactically valid sample against the provided test_cases in an isolated sandbox. Records pass/fail results. Routes to analyze_failures. 
	Execution: CODE. Runs each syntactically valid sample against the provided test_cases in an isolated sandbox. Records pass/fail results. Routes to analyze_failures.
	
	Overview:
	    This node executes each valid code sample in a controlled environment, applying the problem's test cases to verify functional correctness. Runtime exceptions and test failures are captured, and a summary of results is stored for the next stage.
	
	StepÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬ËœbyÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœstep:
	    1. Retrieve valid_samples (state["valid_samples"]) and test_cases (state["test_cases"]) and function_signature (state["function_signature"]).
	    2. Initialise a dictionary test_results mapping sample index to {"passed": bool, "error": optional str}.
	    3. For each sample and its index:
	        a. Call a sandbox helper (e.g., run_code_in_isolated_sandbox) with the sample code, test_cases, and function_signature.
	        b. The helper executes the code, imports the target function, runs each test case, and captures any exceptions.
	        c. Record whether all test cases passed and store any error message.
	    4. Update state with test_results (key "test_results").
	    5. Compute aggregate counts: total_passed and total_failed.
	    6. Route to analyze_failures.
	
	Inputs:
	    - valid_samples (list of str): Syntactically valid code samples.
	    - test_cases (list): Test cases to execute.
	    - function_signature (str): Expected function name and parameters.
	
	Outputs:
	    - test_results (dict): Mapping from sample index to {"passed": bool, "error": optional str}.
	    - total_passed (int): Number of samples that passed all tests.
	    - total_failed (int): Number of samples that failed at least one test.
	
	Possible tools:
	    - None (pure Python code). No ToolNode needed.
	
	Possible helpful functions:
	    - run_code_in_isolated_sandbox(code: str, test_cases: List[str], function_signature: str) -> Dict[str, Any]: Executes the code and runs the test cases, returning pass/fail information.
	"""

    print_function_name()
    try:
        # TODO: <process>
        return ... # TODO: <return>
    except Exception as e:
        print(f'{RED}[NODE] [ERR]{RESET}', e) if DEBUG else None
        traceback.print_exc() if DEBUG else None
        # TODO: <error_handling> if needed
        return state


def analyze_failures(state: AgentSchema) -> AgentSchema:
    """ Execution: LLM. Analyzes test failures and produces repair feedback. Determines whether failures exist and whether they are within the allowed 2ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‹Å“round repair limit. Routes conditionally to repair_samples or finalize_solution. 
	Execution: LLM. Analyzes test failures and produces repair feedback. Determines whether failures exist and whether they are within the allowed 2ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœround repair limit. Routes conditionally to repair_samples or finalize_solution.
	
	Overview:
	    This node uses the analyze_failures_llm to interpret the test results, decide if repairs are still possible, and generate naturalÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœlanguage guidance for the next generation step. It also tracks how many repair rounds have been attempted.
	
	StepÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬ËœbyÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœstep:
	    1. Extract test_results (state["test_results"]), samples (state["samples"]), and optional repair_round (state.get("repair_round", 0)).
	    2. Summarise failures: count of failed samples, common error patterns, and any runtime exceptions.
	    3. Determine if any failures remain (total_failed > 0) and whether repair_round < 2.
	    4. If failures exist and budget remains:
	        a. Set should_repair = True.
	        b. Generate repair_feedback via the LLM, describing what went wrong and how to improve.
	    5. Otherwise:
	        a. Set should_repair = False.
	        b. Produce a finalization message (e.g., "All tests passed" or "Maximum repair rounds reached").
	    6. Update state with repair_feedback (str), should_repair (bool), and optionally increment repair_round.
	    7. Route conditionally to repair_samples (if should_repair) or finalize_solution.
	
	Inputs:
	    - test_results (dict): Output from execute_tests.
	    - samples (list of str): The code samples that were tested.
	    - repair_round (int, optional): Current repair round count (default 0).
	
	Outputs:
	    - repair_feedback (str): Guidance for the LLM on how to fix failing samples.
	    - should_repair (bool): Flag indicating whether a repair step should be triggered.
	    - repair_round (int): Updated repair round count (incremented if repair is performed).
	
	Possible tools:
	    - None (the LLM performs analysis). No ToolNode required.
	
	Possible helpful functions:
	    - None
	"""

    print_function_name()
    try:
        # TODO: <preprocess>
        ... # TODO: <make format arguments readable>
        prompt = prompts.ANALYZE_FAILURES_PROMPT.format(...) # TODO: <formatting>
        result = safe_invoke(analyze_failures_llm, messages= [SystemMessage(content= prompt), ...]) # TODO: <inputs>
        # TODO: <postprocess>
        return ... # TODO: <return>
    except Exception as e:
        print(f'{RED}[NODE] [ERR]{RESET}', e) if DEBUG else None
        traceback.print_exc() if DEBUG else None
        # TODO: <error_handling> if needed
        return state


def repair_samples(state: AgentSchema) -> AgentSchema:
    """ Execution: LLM. If failures exist and within the 2ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‹Å“round limit, regenerates the failing samples using the LLM with repair feedback. Stores updated samples and routes to validate_syntax for reÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â€šÂ¬Ã‹Å“validation. 
	Execution: LLM. If failures exist and within the 2ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœround limit, regenerates the failing samples using the LLM with repair feedback. Stores updated samples and routes to validate_syntax for reÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœvalidation.
	
	Overview:
	    This node receives the repair guidance and regenerates only the samples that previously failed. It preserves the passing samples unchanged, reducing unnecessary work and focusing the LLM on the problematic code.
	
	StepÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬ËœbyÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœstep:
	    1. Retrieve samples (state["samples"]), repair_feedback (state["repair_feedback"]), should_repair (state["should_repair"]), and repair_round (state["repair_round"]).
	    2. If should_repair is False, the node should not be called (controlled by conditional edge).
	    3. Identify failing samples: use repair_feedback and/or test_results (state.get("test_results")) to obtain indices of samples that need fixing.
	    4. Build a repair prompt that includes the original problem specification, the failing code snippets, and the repair_feedback.
	    5. Invoke repair_samples_llm with the prompt to obtain corrected code for each failing sample.
	    6. Replace the failing entries in the samples list with the newly generated code.
	    7. Increment repair_round.
	    8. Update state with the new samples list and the incremented repair_round.
	    9. Route to validate_syntax.
	
	Inputs:
	    - samples (list of str): Current list of code samples.
	    - repair_feedback (str): Guidance on what needs to be fixed.
	    - repair_round (int): Current repair round count.
	    - test_results (dict, optional): To pinpoint which samples failed.
	
	Outputs:
	    - samples (list of str): Updated list with repaired samples.
	    - repair_round (int): Incremented repair round count.
	
	Possible tools:
	    - None (the LLM performs regeneration). No ToolNode required.
	
	Possible helpful functions:
	    - None (prompt creation, parsing, and formatting are excluded per guidelines).
	"""

    print_function_name()
    try:
        # TODO: <preprocess>
        ... # TODO: <make format arguments readable>
        prompt = prompts.REPAIR_SAMPLES_PROMPT.format(...) # TODO: <formatting>
        result = safe_invoke(repair_samples_llm, messages= [SystemMessage(content= prompt), ...]) # TODO: <inputs>
        # TODO: <postprocess>
        return ... # TODO: <return>
    except Exception as e:
        print(f'{RED}[NODE] [ERR]{RESET}', e) if DEBUG else None
        traceback.print_exc() if DEBUG else None
        # TODO: <error_handling> if needed
        return state


def finalize_solution(state: AgentSchema) -> AgentSchema:
    """ Execution: CODE. Compiles the final functional solution as pure Python code, using the original specification fields (function_signature, docstring, test_cases) and any metadata (task_id, version). Routes to end. 
	Execution: CODE. Compiles the final functional solution as pure Python code, using the original specification fields (function_signature, docstring, test_cases) and any metadata (task_id, version). Routes to end.
	
	Overview:
	    This node selects the best performing sample (the first sample that passes all tests) and assembles it into a complete Python function that matches the original problem specification. It also carries forward any metadata such as task_id for downstream benchmark evaluation.
	
	StepÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬ËœbyÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Ëœstep:
	    1. Retrieve function_signature, docstring, test_cases, samples, task_id (optional), and test_results from state.
	    2. If test_results exist, locate the sample with the lowest index where passed == True. If none passed, fall back to the first sample (or raise an error).
	    3. Extract the code body of the chosen sample.
	    4. Use a helper (assemble_solution) to combine the signature, docstring, and code body into a single Python function definition.
	    5. Update state with final_solution (str) and optionally with solution_metadata (dict containing task_id and version).
	    6. Route to end.
	
	Inputs:
	    - function_signature (str): Target function signature.
	    - docstring (str): Problem description.
	    - test_cases (list): Test cases (used only for validation reference).
	    - samples (list of str): All candidate samples.
	    - task_id (optional, str): Identifier for the problem.
	    - test_results (dict, optional): To determine which sample succeeded.
	
	Outputs:
	    - final_solution (str): Complete Python code for the required function.
	    - solution_metadata (dict): Contains task_id and version if present.
	
	Possible tools:
	    - None (pure Python code). No ToolNode needed.
	
	Possible helpful functions:
	    - assemble_solution(function_signature: str, docstring: str, code: str) -> str: Returns a formatted Python function with signature, docstring, and body.
	"""

    print_function_name()
    try:
        # TODO: <process>
        return ... # TODO: <return>
    except Exception as e:
        print(f'{RED}[NODE] [ERR]{RESET}', e) if DEBUG else None
        traceback.print_exc() if DEBUG else None
        # TODO: <error_handling> if needed
        return state





''' Conditional Functions '''
def from_analyze_failures_to(state: AgentSchema) -> Literal["repair_samples", "finalize_solution"]:
    """ TODO: <docstring> """
    print_function_name()
    # TODO: <conditions>



''' Graph '''
problem_solution_pipeline_graph = StateGraph(AgentSchema)

problem_solution_pipeline_graph.add_node("generate_samples", generate_samples)
problem_solution_pipeline_graph.add_node("validate_syntax", validate_syntax)
problem_solution_pipeline_graph.add_node("execute_tests", execute_tests)
problem_solution_pipeline_graph.add_node("analyze_failures", analyze_failures)
problem_solution_pipeline_graph.add_node("repair_samples", repair_samples)
problem_solution_pipeline_graph.add_node("finalize_solution", finalize_solution)

problem_solution_pipeline_graph.add_edge(START, "generate_samples")
problem_solution_pipeline_graph.add_edge("generate_samples", "validate_syntax")
problem_solution_pipeline_graph.add_edge("validate_syntax", "execute_tests")
problem_solution_pipeline_graph.add_edge("execute_tests", "analyze_failures")
problem_solution_pipeline_graph.add_conditional_edges(
    "analyze_failures",
    from_analyze_failures_to,
    {   # Not needed just for clarity
        "repair_samples": "repair_samples",
        "finalize_solution": "finalize_solution",
    }
)
problem_solution_pipeline_graph.add_edge("repair_samples", "validate_syntax")
problem_solution_pipeline_graph.add_edge("finalize_solution", END)


problem_solution_pipeline_app = problem_solution_pipeline_graph.compile(checkpointer= MemorySaver())



''' Testing '''
if __name__ == '__main__':
    from IPython.display import Image as GraphImage

    # Visualize the graph
    GraphImage(problem_solution_pipeline_app.get_graph().draw_mermaid_png(max_retries= 5, retry_delay= 2.0))
    parent_dir = Path(__file__).resolve().parent
    if not os.path.exists(parent_dir / 'graphs'):
        os.makedirs(parent_dir / 'graphs')
    with open(parent_dir / 'graphs/problem_solution_pipeline_app.png', 'wb') as f:
        f.write(problem_solution_pipeline_app.get_graph().draw_mermaid_png())

    
    # Connect to langsmith
    from langsmith import Client
    os.environ['LANGCHAIN_PROJECT'] = 'problem_solution_pipeline'
    os.environ['LANGSMITH_PROJECT'] = 'problem_solution_pipeline'
    client = Client()

    config = {
        'recursion_limit': 100,
        'configurable': {
            'user_id': 'problem_solution_pipeline',
            'run_name': 'problem_solution_pipeline',
            'thread_id': 'problem_solution_pipeline', 
        }
    }

    user = '' # TODO: add
    response = problem_solution_pipeline_app.invoke(user, config= config)

    print(f'{BLUE}[MAIN] [INFO]{RESET} Response') if DEBUG else None
    if DEBUG:
        for key, value in response.items():
            print(f'    {key}: {value}')
